Wham/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.conf.urls import url

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

from meal_count import views

urlpatterns = [
    #path('', include('meal_count.urls')),
    path('admin/', admin.site.urls),
    path('redirect_to_lang_url/', views.redirect_2_lang_url)
    #url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    url(r'^', include('meal_count.urls', namespace='meal-count')),
)

handler404 = 'meal_count.views.handler404'
handler403 = 'meal_count.views.handler403'
handler500 = 'meal_count.views.handler500'

# for Static Files
urlpatterns += staticfiles_urlpatterns()

meal_count/urls.py
#URL config for meal_count app

from django.conf.urls import url
from django.contrib.auth import views as authviews
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LogoutView
from django.utils.translation import ugettext_lazy as _

from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'meal_count'

auth_urlpatterns = ([
    path(_('login/'), authviews.LoginView.as_view(), name='auth_login'),
    path(_('logout/'), authviews.LogoutView.as_view(), name='auth_logout'),

    path(_('password_change/'), authviews.PasswordChangeView.as_view(), name='password_change'),
    path(_('password_change/done/'), authviews.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path(_('password_reset/'), authviews.PasswordResetView.as_view(), name='password_reset'),
    path(_('password_reset/done/'), authviews.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(_('reset/<uidb64>/<token>/'), authviews.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path(_('reset/done/'), authviews.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
], 'auth')

urlpatterns = [
    path('', views.index, name='index'),
    path(_('default'), views.index_default, name='index_default'),
    path(_('guests'), views.guests, name='guests'),
    path(_('guests/delete'), views.delete_guest, name='delete_guest'),
    path(_('view/<str:week_delta>/'), views.index, name='altered_index'),
    path(_('all/'), views.view_all, name='view_all'),
    path(_('all/defaults'), views.view_all_defaults, name='view_all_defaults'),
    path(_('all/<str:week_delta>/'), views.view_all, name='view_all'),
    path('generate', views.generate_dates, name='generate'),
    path(_('update_status'), views.update_status, name='update_status'),
    url(r'^verify/$', views.verify_attendance, name='verify_attendance'),
    path(_('verify/<str:current_meal>/'), views.verify_attendance, name='verify_attendance'),
    path(_('verify/set_act_status'), views.set_act_status, name='set_act_status'),
    path(_('manage'), views.manage, name='manage'),
    path(_('manage/meals'), views.meals, name='manage_meals'),
    path(_('manage/meals/<str:week_delta>/'), views.meals, name='manage_meals'),
    path(_('manage/users'), views.manage_users, name='manage_users'),
    path(_('manage/users/<str:username>'), views.manage_users, name='manage_users'),
    path(_('manage/add_opt'), views.add_option, name='add_statusoption'),
    path(_('manage/del_opt'), views.delete_option, name='delete_statusoption'),
    path(_('manage/del_diet'), views.delete_diet, name='delete_diet'),
    path(_('manage/add_diet'), views.add_diet, name='add_diet'),
    path(_('manage/del_meal'), views.delete_meal, name='delete_meal'),
    path(_('manage/add_meal'), views.add_meal, name='add_meal'),
    path(_('manage/set_override'), views.set_override, name='set_override'),
    path(_('manage/add_message'), views.add_message, name='add_message'),
    path(_('manage/set_email'), views.set_email, name='set_email'),
    path(_('manage/toggle_status'), views.toggle_status_option, name='toggle_status'),
    path(_('manage/change_person_status'), views.change_person_status, name='change_person_status'),
    path(_('<str:center>/report'), views.count_report, name='current_count'),
    path(_('<str:center>/report/week'), lambda request, center: views.count_report(request, center=center, report_type='week'), name='current_count_week'),
    #path(_('<str:center>/classic'), views.classic_report, name='classic_report'),
    path(_('<str:center>/initials'), lambda request, center: views.count_report(request, center=center, is_initials=True), name='initials_report'),
    path(_('<str:center>/initials/week'), lambda request, center: views.count_report(request, center=center, report_type='week', is_initials=True), name='initials_report_week'),
    path('init-meal-count', views.initialize_meal_count, name='initialize_app'),
    path(_('<str:center>/create_account'), views.create_user, name='create_user'),
    path(_('logout'), views.logout_user, name='logout_user'),
    #path('accounts/login/', views.custom_login, name='custom_login'),
    url(_('accounts/profile'), RedirectView.as_view(url='/', permanent=False)),
    path(_('accounts/'), include(auth_urlpatterns)),#'django.contrib.auth.urls')),
]

meal_count/views.py
#The Meal Count App (Formerly WHAM)

import datetime
import timeit
import pytz
from meal_count import tools
from Wham.settings import *
from Wham.parameters import *

from django.shortcuts import render, get_list_or_404, get_object_or_404, render_to_response
from django.template.loader import render_to_string
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.views import auth_login, PasswordResetView
from django.forms.models import model_to_dict
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.utils.translation import activate, get_language_info
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import get_language_from_request, activate
from meal_count.models import Person, Day, Meal, Center, Status, StatusOption, Diet, MealOption
from .forms import CreateUserForm2, NewGuestForm, CreateUserForm1
from .init_app import initialize_app



# NOTE: avoid for loops use complex .filter() calls instead its much faster


def handler404(request, exception, template_name="404.html"):
    response = render_to_response("meal_count/error/404.html")
    response.status_code = 404

    return response


def handler403(request, exception, template_name="403.html"):
    response = render_to_response("meal_count/error/403.html")
    response.status_code = 403
    return response


def handler500(request):  #  exception, template_name="500.html"): This fixes an error on the server side
    response = render_to_response("meal_count/error/500.html")
    response.status_code = 500
    return response


# TODO: hide irrelevant meals/options
####Guest views####

def custom_login(request):
    """
    Use the django auth login view for the login page but redirect to the index after successful login.
    :param request:
    :return:
    """
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    else:
        return auth_login(request)

def custom_pwd_reset(request):
    """
    Use the django auth login view for the login page but redirect to the index after successful login.
    :param request:
    :return:
    """
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    else:
        return PasswordResetView(request)

def clean_url_input(text_str):
    """
    Removes spaces/ capitalization from inputted string.
    :return:
    """
    new_str = text_str.replace(' ', '')  # replaces spaces
    return new_str.lower()

def get_center_from_string(center_n):
    """
    Gets the center from a string.
    :param center_n:
    :return:
    """
    center_name = "null"
    for c in Center.objects.all():
        if clean_url_input(c.name) == clean_url_input(center_n):
            center_name = c.name

    return get_object_or_404(Center, name__iexact=center_name)

def create_user(request, center):
    """Handles the creation of a new user."""

    error_msg = None
    center = get_center_from_string(center)

    if request.method == 'POST':
        # if the form was submitted
        # create model instance
        # TODO: Get first and last name from user instance not person
        # TODO: convert objects.get to .save(commit=false) etc
        user_form = CreateUserForm1(request.POST, prefix='user')
        person_form = CreateUserForm2(request.POST, center_i=center, prefix='person', initial={'active': True, 'center': center})
        if user_form.is_valid():
            print('user_form passed validation')
            user_form.save()

            # TODO: prevent duplicates
            if person_form.is_valid():
                print('person_form passed validation')
                person_obj = person_form.save(commit=False)
                person_obj.center = center
                # FIXME: error handling when duplicate values
                # Get the new person object, connect it to the new user, then save it
                try:
                    user = User.objects.get(username=user_form['username'].value())
                    #person_obj = Person.objects.get(name=person_form['name'].value(), active=True, center=center)
                    # attach user to person object and save
                    person_obj.user = user
                    person_obj.save()
                    # if everything works redirect to login
                    return HttpResponseRedirect('/accounts/login')
                except User.MultipleObjectsReturned:
                    error_msg = _("The username you entered already exists.")
                    print('That username already exists')
                except Person.MultipleObjectsReturned:
                    error_msg = _("The name that you entered is already in the database.")
                    print('That person name already exists')
                except:
                    error_msg = _("Sorry, the account could not be created. Please try again.")

            else:
                #error_msg = person_form.errors
                print('person_from failed validation')

        else:
            error_msg = user_form.errors
            print('user_from failed validation')

    else:
        user_form = CreateUserForm1(prefix='user')  # default user creation form
        person_form = CreateUserForm2(center_i=center, prefix='person')  # custom extension

    # Return create page if it is a GET request or any error occurs
    return render(request, 'registration/create.html', {'user_form': user_form, 'person_form': person_form, 'error_msg':error_msg, 'center_name': center.name})


def count_report(request, center, report_type=None, is_initials=False):
    """Displays the count for the upcoming meals.
    type: if none -> 2 day lookahead; if 'week' -> 7 day lookahead
    is intitals: True: show initials report, False: show just count
    """
    #TODO: require admin priv for initials
    center = get_center_from_string(center)
    center_tz = pytz.timezone(center.timezone)
    now = timezone.localtime(timezone.now(), center_tz)

    if report_type == 'week':
        # look ahead 7x number of meals/day at the center
        look_ahead = len(MealOption.objects.filter(center=center)) * 7
    else:
        # look ahead 2x number of meals/day at the center
        look_ahead = len(MealOption.objects.filter(center=center)) * 2  # number of meals to look ahead

    future_meals = Meal.objects.filter(day__date__gte=now.date(), center=center)
    future_meals = future_meals.order_by('day__date', 'meal_type__meal_time')  # need to sort by date to get them in proper order
    meal_set = future_meals[:look_ahead]

    if is_initials:
        # if it is an initials report set results list to that otherwise do normal report
        results_list = tools.initials(meal_set, center)# [(meal, {diet_name:initials})]
    else:
        results_list = tools.count(meal_set, center)# [(meal, {diet_name:count})]

    ordered_diets = center.diet_set.all().order_by("priority")
    ordered_options = center.statusoption_set.all().order_by("priority")


    num_diets = len(Diet.objects.filter(center=center))  # this is so the title can be centered for each report meal

    context = {'meal_set': meal_set, 'num_diets': num_diets, 'is_initials': is_initials,
               'report_type': report_type, 'center': center,
               'ordered_diets': ordered_diets, 'ordered_options': ordered_options, 'results_list': results_list}

    #Save report page to a html file
    # saved_template_path = os.path.join(SAVED_REPORTS, center.name)
    # if not os.path.exists(saved_template_path):
    #     os.mkdir(saved_template_path)
    # with open(os.path.join(saved_template_path,timezone.datetime.now().strftime("%Y-%m-%d")+'count_report.html'), 'w') as file:
    #     file.write(render_to_string('meal_count/report.html', context, request))
    #   print(render_to_string('meal_count/report.html', context, request))
    return render(request, 'meal_count/report/report.html', context)

# def current_count(request, center):
#     """Displays the count for the upcoming meals."""
#
#     center = get_object_or_404(Center, name__iexact=center)
#     center_tz = pytz.timezone(center.timezone)  # get center's tz, convert it to tz object
#     now = timezone.localtime(timezone.now(), timezone=center_tz)  # use tz aware object for now
#     look_ahead = 12  # number of meals to look ahead
#
#     future_meals = Meal.objects.filter(day__date__gte=now.date())
#     future_meals = future_meals.order_by('day__date')  # need to sort by date to get them in proper order
#     meal_set = future_meals[:look_ahead]
#     results_list = tools.count(meal_set, center)
#
#     num_diets = len(Diet.objects.filter(center=center))  # this is so the title can be centered for each report meal
#
#     return render(request, 'meal_count/main_report.html',
#                   {'meal_set': meal_set, 'results_list': results_list, 'num_diets': num_diets})


def classic_report(request, center):
    """Displays the count for the upcoming meals."""

    center = get_center_from_string(center)
    center_tz = pytz.timezone(center.timezone)  # get center's tz, convert it to tz object
    now = timezone.now()

    future_meals = Meal.objects.filter(day__date__gte=now.date(), center=center)
    future_meals = future_meals.order_by('day__date', 'meal_type__meal_time')  # need to sort by date to get them in proper order
    meal_set = future_meals[:LOOKAHEAD]
    possible_diets = Diet.objects.filter(center=center)  # list of possible diets
    results_list = tools.count(meal_set, center)

meal_count/templates/meal_count/status/index.html
{% extends "meal_count/base.html" %}
{% load staticfiles %}
{% load custom_tags %}
{% load i18n %}
{#HTML Template for the Director management page#}



{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'meal_count/indexstyles.css' %}">
{% endblock %}

{% block scripts %}
    <script>
        {#  Convert django template vars to js vars for use in code#}
        var status_options = {{ all_options|safe }};

    </script>
{% endblock %}

{#Block for nav id to set id to active#}
{% block current-nav-id %}"#home-nav-item"{% endblock %}

{% block content %}
    {#    Success alert/spinner centered on screen in fixed position#}
    <div class="fixed-top mt-4">
        <div class="d-flex justify-content-center">
            <div class="alert alert-success collapse" role="alert"
                 data-dismiss="alert">{% trans "Success!" %}</div>
            <div class="spinner-border collapse" id="status-spinner" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
    </div>
    {#    Pills for page options#}
    <div class="col-md-12 text-center">
        <div class="nav nav-pills center-pills">
            <div class="nav-item dropdown">
                    <a class="nav-link my-2 dropdown-toggle {% if week_delta != "default" %}active{% endif %}" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true"
                       aria-expanded="false">{{ days.0.date|date:"M j" }} - {{ days.last.date|date:"M j" }}</a>
                    <div class="dropdown-menu my-2">
                        <a class="dropdown-item"
                           href="{% url 'meal-count:index' %}">{% trans 'Current meal count' %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item"
                           href="{% url 'meal-count:altered_index' week_delta|add:"-1" %}">{% trans "Previous Week" %}</a>
                        <a class="dropdown-item"
                           href="{% url 'meal-count:altered_index' week_delta|add:"1" %}">{% trans "Next Week" %}</a>
                    </div>
                </div>
{#                {% if perms.person.is_director %}#}
{#                    <div class="nav-item">#}
{#                        <a class="nav-link"#}
{#                           href="{% url 'meal-count:view_all' week_delta %}">{% trans 'All meal counts' %}</a>#}
{#                    </div>#}
{#                {% endif %}#}
                <div class="nav-item my-2">
                    <a class="nav-link {% if week_delta == "default" %}active{% endif %}" href="{% url 'meal-count:index_default' %}">{% trans 'Default meal count' %}</a>
                </div>
        </div>
    </div>
{#   cards for each meal #}
    <div class="container my-5 d-flex flex-row flex-wrap justify-content-center">
        {% csrf_token %}
        {% for day in days %}
            <div class="card mx-2 my-3 standard-card-width">
                <div class="card-body">
                    <h5 class="card-title">
                        {% if week_delta == "default" %}
                            <span class="ct_cell ct-title-cell"
                                <b>{% trans 'Default' %}</b><br>{{ day.date|date:"l" }}<br></span>
                        {% else %}
                            <span class="ct_cell ct-title-cell"><b>
                                {% ifequal day.date today %}{% trans "Today" %}{% else %}
                                    {{ day.date|date:"l" }}{% endifequal %}</b><br>{{ day.date }}<br></span>
                        {% endif %}
                    </h5>
                <div class="list-group list-group-flush">
                    {% for meal in day.meal_set.all|sort_by:'meal_type__meal_time' %}
                        <div class="list-group-item d-inline-flex">
                            <h6 class="w-50">{% trans meal.meal_type.name context "meal" %}</h6>
                            {% with status=meal.status_set|by_person:person %}
                                <button type="button" class="btn btn-primary w-50 ml-2 status-box {% if meal.disabled %}disabled{% endif %} {% if status.edited_at is None %}text-warning{% endif %}" data-url="{% url 'meal-count:update_status' %}" data-s-class="{{ day.id }}-success">
                                    <span class="status-text" id="{{ status.id }}" >{% trans status.status.abbreviation %}</span>
                                </button>
                            {% endwith %}
                        </div>
                    {% endfor %}
                </div>
                </div>
                <div class="card-footer text-muted">
                    {% if day.message is not None %}{% trans day.message %}{% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{#Toolbar for quick select#}
    <div class="btn-toolbar d-flex flex-column position-fixed toolbar-bottom-right mr-2 mb-2" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group-vertical mr-2 tools-selector-group d-none" role="group" aria-label="Selector group">
            {% for option in all_options %}
                <button type="button" class="btn btn-secondary btn-lg tools-option">{% trans option %}</button>
            {% endfor %}
            <button type="button" class="btn btn-secondary btn-lg tools-option active">-</button>
        </div>
        <div class="btn-group-vertical mr-2 mt-1" role="group" aria-label="Indicator group">
            <button type="button" class="btn btn-secondary btn-lg tools-indicator" data-toggle="tooltip" data-placement="left" title="Apply selected option with one click">-</button>
        </div>
    </div>

{% endblock %}

meal_count/templates/meal_count/status/view_all.html
{% extends "meal_count/base.html" %}
{% load staticfiles %}
{% load custom_tags %}
{% load i18n %}
{#HTML Template for the Director management page#}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'meal_count/indexstyles.css' %}">
{% endblock %}

{% block scripts %}
    {#    <script src="{% static 'meal_count/view_allscripts.js' %}"></script>#}
    <script>
        {#  Convert django template vars to js vars for use in code#}
        var status_options = {{ all_options|safe }};
    </script>
{% endblock %}

{% block submenu %}
    {#    This submenu allows user to change the currently viewed week. (increment or decrement by one#}
    {#    if it is current week, hide previous button#}
    {% if week_delta == "default" %}
        {#    If its a default week hide the week_delta links and only show the view_all for the director and the current meal count link#}
        {% if perms.person.is_director %}
            {#        provide way for director to view the meal counts for all the people in the center#}
            <div class="submenu-links">
                <a class="clickable" href="/">{% trans 'Personal meal count' %}</a>
                <a class="clickable" href="{% url "meal-count:view_all" %}">{% trans 'Current meal counts' %}</a>
            </div>
        {% endif %}

    {% else %}
        {% if week_delta != "default" %}
            {% with week_delta|add:"-1" as prev_week %}
                {% if prev_week < 0 %}
                    {#            if the delta is negative add an n before the number to indicate its in the past#}
                    <a href="{% url 'meal-count:view_all' week_delta|add:"-1" %}" title="Previous week">&lt;&lt;</a>
                {% else %}
                    {#            otherwise just show index - 1#}
                    <a href="{% url 'meal-count:view_all' week_delta|add:"-1" %}" title="Previous week">&lt;&lt;</a>
                {% endif %}
            {% endwith %}
            <span>{{ days.0.date|date:"M j" }} - {{ days.last.date|date:"M j" }}</span>
            <a href="{% url 'meal-count:view_all' week_delta|add:"1" %}" title="Next week">&gt;&gt;</a>
        {% endif %}
        {% if perms.person.is_director %}
            {#        Provide way for director to return to personal view#}
            <div class="submenu-links">
                <a class="clickable" href="/">{% trans 'Personal meal count' %}</a>
                <a class="clickable" href="{% url "meal-count:view_all_defaults" %}">{% trans 'All defaults' %}</a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <table class="count_table all-status-table">
        <thead>
        {% csrf_token %}
        <tr>
            <th class="ct_cell"></th>
            {% for person in people %}
                <th class="ct_cell">{{ person.initials }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for day in days %}
            <tr>
                <td class="ct_cell date-cell" colspan="{{ people.all|length|add:"1" }}">
                    {% if week_delta != 'default' %}
                        {% ifequal day.date today %}<b>{% trans "Today" %}</b>{% else %}
                            <b>{{ day.date|date:"l" }}{% endifequal %}</b><br>{{ day.date }}<br></td>
                    {% else %}
                        <b>{{ day.date|date:"l" }}</b>
                        <br>{% trans 'Default' %}<br></td>
                    {% endif %}
            </tr>
            {% if week_delta != 'default' %}
                <tr class="msg-input-row" id="i{{ day.id }}" style="display:none;">
                    {#            Add message input row, hidden initially#}
                    <td class="ct_cell date-cell" colspan="{{ people.all|length|add:"1" }}">
                        {% csrf_token %}
                        <input type="text" class="msg-input" id="in{{ day.id }}" }} maxlength="40"
                               placeholder="{% if day.message %}{{ day.message }}{% else %}{% trans 'Message' %}{% endif %}">
                    </td>
                {# for translation #}
                    <span style="display: none" id="ADDTXT">{% trans "Add" %}</span>
                </tr>
                <tr>
                    {#            Add message link row#}
                    <td class="ct_cell date-cell" colspan="{{ people.all|length|add:"1" }}"><a
                            class="add-message clickable" id="{{ day.id }}" data-url="{% url 'meal-count:add_message' %}">
                        {% if day.message is None or day.message == "" %}{% trans 'New message' %}{% else %}
                            {{ day.message }}{% endif %}</a></td>
                </tr>
            {% endif %}
            {% for meal in day.meal_set.all|sort_by:'meal_type__meal_time' %}
                <tr>
                    <td class="ct_cell">
                        {% csrf_token %}
                        {% trans meal.meal_type.code context "meal"%}<br>
                        <select class="override-sel" id="{{ meal.id }}" onchange="set_override(this, false);" data-url="{% url 'meal-count:set_override' %}">
                            {% for override in overrides %}
                                <option value="{{ override }}"
                                        {% if override == meal.override %}selected{% endif %}>{% trans override %}</option>
                            {% endfor %}
                        </select>
                    {# for translation #}
                        <span id='APWM' style="display: none">{% trans "This will change the status of everyone who is not signed in as 'absent' to 'packed.' To undo this, users will have to reenter their original status for this meal. Do you wish to continue?" %}</span>

                        {#                        Text input and button for the manual count entry#}
                        <div class="manual-entry" id="me{{ meal.id }}"
                             {% if meal.override != "Manual Count" %}style="display: none;"{% endif %}>
                            <input class="manual-count-input" type="number" id="mi{{ meal.id }}"
                                   placeholder="{{ meal.manual_count }}" maxlength="2">
                            <br>
                            {#                                use onclick so that only one function has to be used#}
                            {#                                If clicked send the input not the link#}
                            <a class="clickable manual-set" id="m{{ meal.id }}"
                               onclick="set_override($('#{{ meal.id }}').get(0), true);">{% trans 'Set count' %}</a>
                        </div>
                    </td>
                    {% for person in people %}
                        {% with status=meal.status_set|by_person:person %}

                            {#                                Account for those persons who don't have statuses for certain meals (show N/A)#}
                            {% if status == None %}
                                <td class="ct_cell status-box disabled">N/A</td>
                            {% else %}
                                <td class="ct_cell status-box
                                                {% if meal.disabled %}{% else %}clickable{% endif %}" data-url="{% url 'meal-count:update_status' %}">
                                    {#                                    NOTE: this span can't have any special characters, so it has to be a single line with no spaces#}
                                    <span class="status-text" id="{{ status.id }}"
                                          style="{% if status.edited_at is None %}color:blue;{% endif %}">{% trans status.status.abbreviation %}</span>
                                </td>
                            {% endif %}

                        {% endwith %}
                    {% endfor %}
                </tr>
            {% endfor %}


        {% endfor %}
        </tbody>
    </table>
    </div>
    {# A fixed icon in the lower right corner that allows for quick modification of status#}
    <div class="tools-container">
    {% for option in all_options %}
        <div class="tools-option" style="display: none;">
            <div class="tools-text">{% trans option %}</div>
        </div>
    {% endfor %}
    {#    Blank div to be populated with active tool#}
    <div id="tools-active">
        <div class="tools-text">-</div>
    </div>
    </div>
{% endblock %}