Wham/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.conf.urls import url

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

from meal_count import views

urlpatterns = [
    #path('', include('meal_count.urls')),
    path('admin/', admin.site.urls),
    path('redirect_to_lang_url/', views.redirect_2_lang_url)
    #url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    url(r'^', include('meal_count.urls', namespace='meal-count')),
)

handler404 = 'meal_count.views.handler404'
handler403 = 'meal_count.views.handler403'
handler500 = 'meal_count.views.handler500'

# for Static Files
urlpatterns += staticfiles_urlpatterns()

meal_count/urls.py
#URL config for meal_count app

from django.conf.urls import url
from django.contrib.auth import views as authviews
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LogoutView
from django.utils.translation import ugettext_lazy as _

from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'meal_count'

auth_urlpatterns = ([
    path(_('login/'), authviews.LoginView.as_view(), name='auth_login'),
    path(_('logout/'), authviews.LogoutView.as_view(), name='auth_logout'),

    path(_('password_change/'), authviews.PasswordChangeView.as_view(), name='password_change'),
    path(_('password_change/done/'), authviews.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path(_('password_reset/'), authviews.PasswordResetView.as_view(), name='password_reset'),
    path(_('password_reset/done/'), authviews.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(_('reset/<uidb64>/<token>/'), authviews.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path(_('reset/done/'), authviews.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
], 'auth')

urlpatterns = [
    path('', views.index, name='index'),
    path(_('default'), views.index_default, name='index_default'),
    path(_('guests'), views.guests, name='guests'),
    path(_('guests/delete'), views.delete_guest, name='delete_guest'),
    path(_('view/<str:week_delta>/'), views.index, name='altered_index'),
    path(_('all/'), views.view_all, name='view_all'),
    path(_('all/defaults'), views.view_all_defaults, name='view_all_defaults'),
    path(_('all/<str:week_delta>/'), views.view_all, name='view_all'),
    path('generate', views.generate_dates, name='generate'),
    path(_('update_status'), views.update_status, name='update_status'),
    url(r'^verify/$', views.verify_attendance, name='verify_attendance'),
    path(_('verify/<str:current_meal>/'), views.verify_attendance, name='verify_attendance'),
    path(_('verify/set_act_status'), views.set_act_status, name='set_act_status'),
    path(_('manage'), views.manage, name='manage'),
    path(_('manage/meals'), views.meals, name='manage_meals'),
    path(_('manage/meals/<str:week_delta>/'), views.meals, name='manage_meals'),
    path(_('manage/users'), views.manage_users, name='manage_users'),
    path(_('manage/users/<str:username>'), views.manage_users, name='manage_users'),
    path(_('manage/add_opt'), views.add_option, name='add_statusoption'),
    path(_('manage/del_opt'), views.delete_option, name='delete_statusoption'),
    path(_('manage/del_diet'), views.delete_diet, name='delete_diet'),
    path(_('manage/add_diet'), views.add_diet, name='add_diet'),
    path(_('manage/del_meal'), views.delete_meal, name='delete_meal'),
    path(_('manage/add_meal'), views.add_meal, name='add_meal'),
    path(_('manage/set_override'), views.set_override, name='set_override'),
    path(_('manage/add_message'), views.add_message, name='add_message'),
    path(_('manage/set_email'), views.set_email, name='set_email'),
    path(_('manage/toggle_status'), views.toggle_status_option, name='toggle_status'),
    path(_('manage/change_person_status'), views.change_person_status, name='change_person_status'),
    path(_('<str:center>/report'), views.count_report, name='current_count'),
    path(_('<str:center>/report/week'), lambda request, center: views.count_report(request, center=center, report_type='week'), name='current_count_week'),
    #path(_('<str:center>/classic'), views.classic_report, name='classic_report'),
    path(_('<str:center>/initials'), lambda request, center: views.count_report(request, center=center, is_initials=True), name='initials_report'),
    path(_('<str:center>/initials/week'), lambda request, center: views.count_report(request, center=center, report_type='week', is_initials=True), name='initials_report_week'),
    path('init-meal-count', views.initialize_meal_count, name='initialize_app'),
    path(_('<str:center>/create_account'), views.create_user, name='create_user'),
    path(_('logout'), views.logout_user, name='logout_user'),
    #path('accounts/login/', views.custom_login, name='custom_login'),
    url(_('accounts/profile'), RedirectView.as_view(url='/', permanent=False)),
    path(_('accounts/'), include(auth_urlpatterns)),#'django.contrib.auth.urls')),
]

meal_count/views.py
#The Meal Count App (Formerly WHAM)

import datetime
import timeit
import pytz
from meal_count import tools
from Wham.settings import *
from Wham.parameters import *

from django.shortcuts import render, get_list_or_404, get_object_or_404, render_to_response
from django.template.loader import render_to_string
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.views import auth_login, PasswordResetView
from django.forms.models import model_to_dict
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.utils.translation import activate, get_language_info
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import get_language_from_request, activate
from meal_count.models import Person, Day, Meal, Center, Status, StatusOption, Diet, MealOption
from .forms import CreateUserForm2, NewGuestForm, CreateUserForm1
from .init_app import initialize_app



# NOTE: avoid for loops use complex .filter() calls instead its much faster


def handler404(request, exception, template_name="404.html"):
    response = render_to_response("meal_count/error/404.html")
    response.status_code = 404

    return response


def handler403(request, exception, template_name="403.html"):
    response = render_to_response("meal_count/error/403.html")
    response.status_code = 403
    return response


def handler500(request):  #  exception, template_name="500.html"): This fixes an error on the server side
    response = render_to_response("meal_count/error/500.html")
    response.status_code = 500
    return response


# TODO: hide irrelevant meals/options
####Guest views####

def custom_login(request):
    """
    Use the django auth login view for the login page but redirect to the index after successful login.
    :param request:
    :return:
    """
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    else:
        return auth_login(request)

def custom_pwd_reset(request):
    """
    Use the django auth login view for the login page but redirect to the index after successful login.
    :param request:
    :return:
    """
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    else:
        return PasswordResetView(request)

def clean_url_input(text_str):
    """
    Removes spaces/ capitalization from inputted string.
    :return:
    """
    new_str = text_str.replace(' ', '')  # replaces spaces
    return new_str.lower()

def get_center_from_string(center_n):
    """
    Gets the center from a string.
    :param center_n:
    :return:
    """
    center_name = "null"
    for c in Center.objects.all():
        if clean_url_input(c.name) == clean_url_input(center_n):
            center_name = c.name

    return get_object_or_404(Center, name__iexact=center_name)

def create_user(request, center):
    """Handles the creation of a new user."""

    error_msg = None
    center = get_center_from_string(center)

    if request.method == 'POST':
        # if the form was submitted
        # create model instance
        # TODO: Get first and last name from user instance not person
        # TODO: convert objects.get to .save(commit=false) etc
        user_form = CreateUserForm1(request.POST, prefix='user')
        person_form = CreateUserForm2(request.POST, center_i=center, prefix='person', initial={'active': True, 'center': center})
        if user_form.is_valid():
            print('user_form passed validation')
            user_form.save()

            # TODO: prevent duplicates
            if person_form.is_valid():
                print('person_form passed validation')
                person_obj = person_form.save(commit=False)
                person_obj.center = center
                # FIXME: error handling when duplicate values
                # Get the new person object, connect it to the new user, then save it
                try:
                    user = User.objects.get(username=user_form['username'].value())
                    #person_obj = Person.objects.get(name=person_form['name'].value(), active=True, center=center)
                    # attach user to person object and save
                    person_obj.user = user
                    person_obj.save()
                    # if everything works redirect to login
                    return HttpResponseRedirect('/accounts/login')
                except User.MultipleObjectsReturned:
                    error_msg = _("The username you entered already exists.")
                    print('That username already exists')
                except Person.MultipleObjectsReturned:
                    error_msg = _("The name that you entered is already in the database.")
                    print('That person name already exists')
                except:
                    error_msg = _("Sorry, the account could not be created. Please try again.")

            else:
                #error_msg = person_form.errors
                print('person_from failed validation')

        else:
            error_msg = user_form.errors
            print('user_from failed validation')

    else:
        user_form = CreateUserForm1(prefix='user')  # default user creation form
        person_form = CreateUserForm2(center_i=center, prefix='person')  # custom extension

    # Return create page if it is a GET request or any error occurs
    return render(request, 'registration/create.html', {'user_form': user_form, 'person_form': person_form, 'error_msg':error_msg, 'center_name': center.name})


def count_report(request, center, report_type=None, is_initials=False):
    """Displays the count for the upcoming meals.
    type: if none -> 2 day lookahead; if 'week' -> 7 day lookahead
    is intitals: True: show initials report, False: show just count
    """
    #TODO: require admin priv for initials
    center = get_center_from_string(center)
    center_tz = pytz.timezone(center.timezone)
    now = timezone.localtime(timezone.now(), center_tz)

    if report_type == 'week':
        # look ahead 7x number of meals/day at the center
        look_ahead = len(MealOption.objects.filter(center=center)) * 7
    else:
        # look ahead 2x number of meals/day at the center
        look_ahead = len(MealOption.objects.filter(center=center)) * 2  # number of meals to look ahead

    future_meals = Meal.objects.filter(day__date__gte=now.date(), center=center)
    future_meals = future_meals.order_by('day__date', 'meal_type__meal_time')  # need to sort by date to get them in proper order
    meal_set = future_meals[:look_ahead]

    if is_initials:
        # if it is an initials report set results list to that otherwise do normal report
        results_list = tools.initials(meal_set, center)# [(meal, {diet_name:initials})]
    else:
        results_list = tools.count(meal_set, center)# [(meal, {diet_name:count})]

    ordered_diets = center.diet_set.all().order_by("priority")
    ordered_options = center.statusoption_set.all().order_by("priority")


    num_diets = len(Diet.objects.filter(center=center))  # this is so the title can be centered for each report meal

    context = {'meal_set': meal_set, 'num_diets': num_diets, 'is_initials': is_initials,
               'report_type': report_type, 'center': center,
               'ordered_diets': ordered_diets, 'ordered_options': ordered_options, 'results_list': results_list}

    #Save report page to a html file
    # saved_template_path = os.path.join(SAVED_REPORTS, center.name)
    # if not os.path.exists(saved_template_path):
    #     os.mkdir(saved_template_path)
    # with open(os.path.join(saved_template_path,timezone.datetime.now().strftime("%Y-%m-%d")+'count_report.html'), 'w') as file:
    #     file.write(render_to_string('meal_count/report.html', context, request))
    #   print(render_to_string('meal_count/report.html', context, request))
    return render(request, 'meal_count/report/report.html', context)

# def current_count(request, center):
#     """Displays the count for the upcoming meals."""
#
#     center = get_object_or_404(Center, name__iexact=center)
#     center_tz = pytz.timezone(center.timezone)  # get center's tz, convert it to tz object
#     now = timezone.localtime(timezone.now(), timezone=center_tz)  # use tz aware object for now
#     look_ahead = 12  # number of meals to look ahead
#
#     future_meals = Meal.objects.filter(day__date__gte=now.date())
#     future_meals = future_meals.order_by('day__date')  # need to sort by date to get them in proper order
#     meal_set = future_meals[:look_ahead]
#     results_list = tools.count(meal_set, center)
#
#     num_diets = len(Diet.objects.filter(center=center))  # this is so the title can be centered for each report meal
#
#     return render(request, 'meal_count/main_report.html',
#                   {'meal_set': meal_set, 'results_list': results_list, 'num_diets': num_diets})


def classic_report(request, center):
    """Displays the count for the upcoming meals."""

    center = get_center_from_string(center)
    center_tz = pytz.timezone(center.timezone)  # get center's tz, convert it to tz object
    now = timezone.now()

    future_meals = Meal.objects.filter(day__date__gte=now.date(), center=center)
    future_meals = future_meals.order_by('day__date', 'meal_type__meal_time')  # need to sort by date to get them in proper order
    meal_set = future_meals[:LOOKAHEAD]
    possible_diets = Diet.objects.filter(center=center)  # list of possible diets
    results_list = tools.count(meal_set, center)

meal_count/templates/meal_count/Management/guests.html
{% extends "meal_count/base.html" %}
{% load staticfiles %}
{% load custom_tags %}
{% load i18n %}
{#HTML Template for the Director management page#}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'meal_count/gueststyles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'meal_count/style.css' %}">
{% endblock %}

{% block scripts %}
    <script src="{% static 'meal_count/guest_scripts.js' %}"></script>
{% endblock %}

{% block submenu %}

{% endblock %}

{#Block for nav id to set id to active#}
{% block current-nav-id %}"#guest-nav-item"{% endblock %}

{% block content %}
    <div class="modal" id="confirm-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Confirm Deletion" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{% trans "Are you sure you want to delete this guest?" %}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" id="delete-confirm" data-delete-id=""
                            data-url="{% url 'meal-count:delete_guest' %}"
                            data-url2="{% url 'meal-count:guests' %}">{% trans "Delete" %}</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"
                            id="delete-cancel">{% trans "Cancel" %}</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container my-5 d-flex flex-row flex-wrap justify-content-center">
        <div class="accordion w-75" id="guest-accordion">
            {#        Card for new guest#}
            <div class="card">
                <form action="{% url 'meal-count:guests' %}" method="post" id="add-guest-form">
                    {% csrf_token %}
                    <div class="card-header d-flex justify-content-between align-items-center" id="head-{{ guest.id }}">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                                    data-target="#coll-{{ guest.id }}" aria-expanded="true" aria-controls="collapseOne">
                                {% trans "Add Guest" %}
                            </button>
                        </h2>
                    </div>
                    <div id="coll-{{ guest.id }}" class="card-body collapse show" data-parent="#guest-accordion">
                        <div class="list-group list-group-horizontal flex-wrap">
                            <div class="list-group-item flex-fill border">
                                <div class="list-group list-group-flush">
                                    <div class="list-group-item">
                                        <div class="font-weight-bold">{% trans "Name" %}</div>
                                        <div class="">
                                            <div class="">{{ guest_form.name }}</div>
                                        </div>
                                    </div>
                                    <div class="list-group-item">
                                        <div class="font-weight-bold">{{ guest_form.initials }}</div>
                                        <div class="">{{ guest.initials }}</div>
                                    </div>
                                </div>

                            </div>
                            <div class="list-group-item flex-fill border">
                                <div class="font-weight-bold">{% trans "Diet" %}</div>
                                <div class="">{{ guest_form.diet }}</div>
                            </div>
                            <div class="list-group-item flex-fill border">
                                <div class="font-weight-bold">{% trans "Meals" %}</div>
                                <span class="text-center mx-auto">{{ guest_form.meals }}</span><br>
                            </div>
                        </div>
                        <div class="mt-2">
                            <input class="btn btn-primary" type="submit" value="{% trans 'Add Guest' %}"
                                   class="submit-input">
                        </div>
                    </div>
                </form>
            </div>

            {#        Cards for existing guests#}
            {% for guest in guests %}
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center" id="head-{{ guest.id }}">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                                    data-target="#coll-{{ guest.id }}" aria-expanded="true"
                                    aria-controls="collapse-{{ guest.id }}" data-parent="#guest-accordion">
                                {{ guest.name }}
                            </button>
                        </h2>
                        <h5><span class="badge badge-primary">Meals: {{ guest.meals.count }}</span></h5>
                    </div>
                    <div id="coll-{{ guest.id }}" class="card-body collapse">
                        <div class="list-group list-group-horizontal flex-wrap">
                            <div class="list-group-item flex-fill border">
                                <div class="font-weight-bold">{% trans "Initials" %}</div>
                                <div class="">{{ guest.initials }}</div>
                            </div>
                            <div class="list-group-item flex-fill border">
                                <div class="font-weight-bold">{% trans "Diet" %}</div>
                                <div class="">{{ guest.diet.name }}</div>
                            </div>
                            <div class="list-group-item flex-fill border">
                                <div class="font-weight-bold">{% trans "Meals" %}</div>
                                {% for meal in guest.meals.all %}
                                    <span class="text-center mx-auto">{{ meal }}</span><br>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="mt-2">
                            <a class="btn btn-primary delete-link" id="{{ guest.id }}" href="#">{% trans "Delete" %}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}