Wham/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.conf.urls import url

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

from meal_count import views

urlpatterns = [
    #path('', include('meal_count.urls')),
    path('admin/', admin.site.urls),
    path('redirect_to_lang_url/', views.redirect_2_lang_url)
    #url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    url(r'^', include('meal_count.urls', namespace='meal-count')),
)

handler404 = 'meal_count.views.handler404'
handler403 = 'meal_count.views.handler403'
handler500 = 'meal_count.views.handler500'

# for Static Files
urlpatterns += staticfiles_urlpatterns()

meal_count/urls.py
#URL config for meal_count app

from django.conf.urls import url
from django.contrib.auth import views as authviews
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LogoutView
from django.utils.translation import ugettext_lazy as _

from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'meal_count'

auth_urlpatterns = ([
    path(_('login/'), authviews.LoginView.as_view(), name='auth_login'),
    path(_('logout/'), authviews.LogoutView.as_view(), name='auth_logout'),

    path(_('password_change/'), authviews.PasswordChangeView.as_view(), name='password_change'),
    path(_('password_change/done/'), authviews.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path(_('password_reset/'), authviews.PasswordResetView.as_view(), name='password_reset'),
    path(_('password_reset/done/'), authviews.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(_('reset/<uidb64>/<token>/'), authviews.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path(_('reset/done/'), authviews.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
], 'auth')

urlpatterns = [
    path('', views.index, name='index'),
    path(_('default'), views.index_default, name='index_default'),
    path(_('guests'), views.guests, name='guests'),
    path(_('guests/delete'), views.delete_guest, name='delete_guest'),
    path(_('view/<str:week_delta>/'), views.index, name='altered_index'),
    path(_('all/'), views.view_all, name='view_all'),
    path(_('all/defaults'), views.view_all_defaults, name='view_all_defaults'),
    path(_('all/<str:week_delta>/'), views.view_all, name='view_all'),
    path('generate', views.generate_dates, name='generate'),
    path(_('update_status'), views.update_status, name='update_status'),
    url(r'^verify/$', views.verify_attendance, name='verify_attendance'),
    path(_('verify/<str:current_meal>/'), views.verify_attendance, name='verify_attendance'),
    path(_('verify/set_act_status'), views.set_act_status, name='set_act_status'),
    path(_('manage'), views.manage, name='manage'),
    path(_('manage/meals'), views.meals, name='manage_meals'),
    path(_('manage/meals/<str:week_delta>/'), views.meals, name='manage_meals'),
    path(_('manage/users'), views.manage_users, name='manage_users'),
    path(_('manage/users/<str:username>'), views.manage_users, name='manage_users'),
    path(_('manage/add_opt'), views.add_option, name='add_statusoption'),
    path(_('manage/del_opt'), views.delete_option, name='delete_statusoption'),
    path(_('manage/del_diet'), views.delete_diet, name='delete_diet'),
    path(_('manage/add_diet'), views.add_diet, name='add_diet'),
    path(_('manage/del_meal'), views.delete_meal, name='delete_meal'),
    path(_('manage/add_meal'), views.add_meal, name='add_meal'),
    path(_('manage/set_override'), views.set_override, name='set_override'),
    path(_('manage/add_message'), views.add_message, name='add_message'),
    path(_('manage/set_email'), views.set_email, name='set_email'),
    path(_('manage/toggle_status'), views.toggle_status_option, name='toggle_status'),
    path(_('manage/change_person_status'), views.change_person_status, name='change_person_status'),
    path(_('<str:center>/report'), views.count_report, name='current_count'),
    path(_('<str:center>/report/week'), lambda request, center: views.count_report(request, center=center, report_type='week'), name='current_count_week'),
    #path(_('<str:center>/classic'), views.classic_report, name='classic_report'),
    path(_('<str:center>/initials'), lambda request, center: views.count_report(request, center=center, is_initials=True), name='initials_report'),
    path(_('<str:center>/initials/week'), lambda request, center: views.count_report(request, center=center, report_type='week', is_initials=True), name='initials_report_week'),
    path('init-meal-count', views.initialize_meal_count, name='initialize_app'),
    path(_('<str:center>/create_account'), views.create_user, name='create_user'),
    path(_('logout'), views.logout_user, name='logout_user'),
    #path('accounts/login/', views.custom_login, name='custom_login'),
    url(_('accounts/profile'), RedirectView.as_view(url='/', permanent=False)),
    path(_('accounts/'), include(auth_urlpatterns)),#'django.contrib.auth.urls')),
]

meal_count/models.py
from datetime import time

from Wham.parameters import *
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from django.utils.translation import ugettext_lazy as _

def default_cutoff_time():
    """Function that returns the default cutoff time (8am)"""
    return time(hour=8)


class Center(models.Model):
    '''Model that contains all data for a center.'''
    name = models.CharField(max_length=20, default='Schuyler')
    directors_email = models.EmailField(default='giuntini1996@gmail.com')
    created_at = models.DateTimeField(auto_now_add=True)
    timezone = models.CharField(default=DEFAULT_TZ, max_length=40)
    #lang_code = models.CharField(default='en', max_length=10)

    # Center's settings
    show_count_in_initials = models.BooleanField(default=True, null=True)

    def __str__(self):
        """Make useful str name"""
        return self.name

    def save(self, *args, **kwargs):
        """Overwrite save function to generate default StatusOption for the new user"""

        if not self.pk:
            # if no id, this is a new instance
            super().save(*args, **kwargs)  # must put this here so that person is saved before itis used

            # Create these defaults on creation of the center
            StatusOption(name=_('Absent'), abbreviation=_('O'), priority=0, prep_time=0, center=self, can_edit=False, active=True).save()
            StatusOption(name=_('Present'), abbreviation=_('X'), priority=3, center=self, can_edit=False, active=True).save()
            StatusOption(name=_('Packed'), abbreviation=_('P'), priority=4, center=self, can_edit=False, active=True).save()
            StatusOption(name=_('Late'), abbreviation=_('L'), priority=5, center=self, can_edit=False, active=True).save()
            StatusOption(name=_('Early'), abbreviation=_('E'), priority=6, center=self, can_edit=False, active=True).save()
            StatusOption(name=_('Early Packed'), abbreviation=_('EP'), priority=7, center=self, can_edit=False, active=True).save()
            StatusOption(name=_('Packed before Breakfast'), abbreviation=_('PPB'), priority=1, center=self, can_edit=False,
                         active=True, calculated=True).save()
            StatusOption(name='Packed at Breakfast', abbreviation=_('PAB'), priority=2, center=self, can_edit=False,
                         active=True, calculated=True).save()
            Diet(center=self, name=_('None'), code='N').save()
            MealOption(name=_('Breakfast'), code='B', center=self,
                       cutoff_time=time(hour=8), cutoff_day=1, meal_time=time(hour=8), can_edit=False).save()
            MealOption(name=_('Lunch'), code='L', center=self,
                       cutoff_time=time(hour=8), meal_time=time(hour=12), can_edit=False).save()
            MealOption(name=_('Dinner'), code='D', center=self,
                       cutoff_time=time(hour=12), meal_time=time(hour=19), can_edit=False).save()

        super().save(*args, **kwargs)


class Diet(models.Model):
    """Model for a diet. Contains diet code and description."""
    name = models.CharField(max_length=16, default='None')
    code = models.CharField(max_length=6, default='N')  # lettered/numbered code for diet
    description = models.CharField(max_length=60, default='No diet', blank=True)
    can_edit = models.BooleanField(default=True)
    priority = models.IntegerField(default=100, blank=True)
    center = models.ForeignKey(Center, on_delete=models.CASCADE)

    def __str__(self):
        """Make useful str name"""
        return self.name #+ ' - ' + self.center.name


class Day(models.Model):
    '''Model for a single day. Contains date, day of the week, and occasion'''
    date = models.DateField()
    message = models.CharField(default=None, null=True, max_length=40, blank=True)  # message to be displayed to users

    center = models.ForeignKey(Center, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        """Overwrite save function to generate statuses for the new user"""

        if self.pk is None:
            # if there is no id, the instance is new
            super().save(*args, **kwargs)  # must put this here so that person is saved before itis used

            # generate new Meal instances
            for option in MealOption.objects.filter(center=self.center):
                new_meal = Meal(meal_type=option, day=self, center=self.center)
                new_meal.save()

                absent_status = StatusOption.objects.get(name='Absent', center=self.center)  # get the default status option
                for person in Person.objects.filter(center=self.center, active=True, guest=False):  # cycle through all people in the center ignoring inactive people and guests
                    # create new status for each meal and each person
                    Status(status=absent_status, person=person, meal=new_meal).save()

        super().save(*args, **kwargs)  # this has to be called after checking for pk, b/c this creates it

    def __str__(self):
        """Make useful str name"""
        return self.date.strftime("%b %d %Y") + ' - ' + self.center.name


class MealOption(models.Model):
    """A type of meal (b,l,d,etc)"""
    name = models.CharField(max_length=10, default='Breakfast')
    code = models.CharField(max_length=4, default='B')  # code for meal:  B,L,D
    created_at = models.DateTimeField(auto_now_add=True)  # date that person was created
    cutoff_time = models.TimeField(null=True, default=default_cutoff_time)  # time at which meal gets disabled
    cutoff_day = models.IntegerField(default=0)  # number of days before the meal that the cutoff time activates
    meal_time = models.TimeField(null=True)  # time of the meal
    can_edit = models.BooleanField(default=True)

    center = models.ForeignKey(Center, on_delete=models.CASCADE)

    def __str__(self):
        """Make useful str name"""
        return self.name + ' - ' + self.center.name

    def save(self, *args, **kwargs):
        """Overwrite save function to generate meals for the users when a new option is created"""

        if self.pk is None:
            # if there is no id, the instance is new
            super().save(*args, **kwargs)  # must put this here so that person is saved before it is used

            for day in Day.objects.filter(center=self.center):
                # For each day generate a new meal
                absent_status = StatusOption.objects.get(name='Absent', center=self.center)  # get the default status option
                new_meal = Meal(meal_type=self, day=day, center=self.center)
                new_meal.save()
                for person in Person.objects.filter(center=self.center, active=True):  # cycle through all people in the center
                    # create new status for each person
                    Status(status=absent_status, person=person, meal=new_meal).save()

        super().save(*args, **kwargs)


class Meal(models.Model):
    """Models for a datapoint. Contains status for that meal and date of that meal.
    This is the most basic model. This is a specific instance of a meal."""

    # code = models.CharField(max_length=2, default='B')
    updated_at = models.DateTimeField(auto_now=True)
    disabled = models.BooleanField(default=False)  # indicates whether the meal status can be changed
    override = models.CharField(default=None, null=True, max_length=15, blank=True)  # specifies exceptions when counting
    manual_count = models.IntegerField(default=0, null=True, blank=True)  # indicates the number of people present for manual override
    message = models.CharField(default=None, null=True, max_length=300, blank=True)  # message for administration

    center = models.ForeignKey(Center, on_delete=models.CASCADE, default=None, null=True)
    meal_type = models.ForeignKey(MealOption, on_delete=models.CASCADE, null=True)  # Link to mealoption model
    day = models.ForeignKey(Day, on_delete=models.CASCADE, default=None)  # link to Day model

    def __str__(self):
        """Make useful str name"""
        return self.day.date.strftime("%b %d %Y") + ' - ' + self.meal_type.code


class Person(models.Model):
    """Model for an individual. Contains their name, initials, diet. Extends django User class"""
    name = models.CharField(max_length=20, default='', null=True)
    initials = models.CharField(max_length=3, default='', null=True)
    guest = models.BooleanField(default=False)  # if true the user is a guest
    created_at = models.DateTimeField(auto_now_add=True)  # date that person was created
    active = models.BooleanField(default=True)  # if false the user is ignored in everything (basically a way to delete without deleting

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)  # link to user
    center = models.ForeignKey(Center, on_delete=models.CASCADE, null=True)
    diet = models.ForeignKey(Diet, on_delete=models.CASCADE)  # link to diet model
    meals = models.ManyToManyField(Meal)  # for the guest user

    def save(self, *args, **kwargs):
        """Overwrite save function to generate statuses for the new user"""
        if not self.pk:
            # if no id, this is a new instance
            super().save(*args, **kwargs)  # must put this here so that person is saved before itis used
            # if there is no id, the instance is new

            if not self.guest:
                # get all present and future days for the current center
                future_days = self.center.day_set.filter(date__gte=timezone.now().date())
                absent_status = StatusOption.objects.get(name='Absent', center=self.center)  # get the default status option

                for day in future_days:
                    # loop through future days and meals generating statuses for the new person
                    for meal in day.meal_set.all():

meal_count/templates/meal_count/base.html
{% load static %}
{% load custom_tags %}
{% load i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<!-- Current language: {{ LANGUAGE_CODE }} -->
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <title>{% block title %}TMCA - The Meal Count App{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'meal_count/images/favicon.ico' %}"/>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'meal_count/images/apple-touch-icon.png' %}">
    <link rel="icon" sizes="192x192" href="{% static 'meal_count/images/apple-touch-icon.png' %}">
    <meta charset="UTF-8">
    <meta name="description" content="Schuyler meal count">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{# TODO: make font-awesome available offline#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'meal_count/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block styles %}{% endblock %}
{#FIXME figure out way to put specific style scripts in specific templates not base#}
{#    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" type="text/javascript"></script>#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" type="text/javascript"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" type="text/javascript"></script>
{#    #}
{#    Work around if offline: use pycharm copy of jquery#}

{#    <script src="/static/meal_count/jquery.js"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/floatthead/2.1.3/jquery.floatThead.js"></script>#}

    {% block scripts %}{% endblock %}
    <script src="{% static 'meal_count/main_scripts.js' %}"></script>

</head>

{#NOTE: Page must be refreshed for active links to change#}

<body>
    <header>
{#        Responsive navigational bar taken from https://www.w3schools.com/howto/howto_js_topnav_responsive.asp#}
        <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
{#        use this to highlight links if active {% ifequal request.path "/"%}class="active"{% endifequal %}#}
        {% if user.is_authenticated %}
            <a class="navbar-brand text-primary" href="/" >{% trans "Meal Count" %}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id='home-nav-item' href="{% url 'meal-count:index' %}"
                   title="Add/modify guests (people without accounts)">{% trans "Home" %}</a>

                <a class="nav-item nav-link" id='guest-nav-item' href="{% url 'meal-count:guests' %}" title="Add/modify guests (people without accounts)">{% trans "Guests" %}</a>
    {#            TODO: change permissions#}
                {%  if user.is_authenticated %}
                    <a class="nav-item nav-link" id='report-nav-item' href="{% url 'meal-count:current_count'  user.person.center.name %}" >{% trans "Report" %}</a>
{#                    <a class="nav-item nav-link" id='ireport-nav-item' href="{% url 'meal-count:initials_report' user.person.center.name %}" >{% trans "Initials Report" %}</a>#}
                    <a class="nav-item nav-link" id='verify-nav-item' href="{% url 'meal-count:verify_attendance' %}" >{% trans "Verify" %}</a>
                {% endif %}
                {%  if user.is_superuser %}
                    <a class="nav-item nav-link" id='meals-nav-item' href="{% url 'meal-count:manage_meals' %}" >{% trans "Meals" %}</a>
    {#                <a href="/manage">Manage</a>#}
                    <a class="nav-item nav-link" href="/admin">{% trans 'Django Admin' %}</a>
                {% endif %}
            </div>
            <div class="navbar-nav ml-auto">
    {#        TODO: change username to full name#}
                <a class="nav-item nav-link " href="{% url 'meal-count:auth:auth_logout' %}" id="account" >{% trans 'Logout,' %} {% if user.is_authenticated %}{{ user.username }}{% endif %}</a>
            </div>
    {#            <span>{% now "SHORT_DATETIME_FORMAT" %}</span>#}

            </div>
            {% else %}
                <a class="navbar-brand" href="/" >{% trans "Meal Count" %}</a>
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link " href="{% url 'meal-count:auth:auth_login' %}" id="account" >{% trans 'Login' %}</a>
                </div>
            {% endif %}
        </nav>
{#    Block where script is located to activate#}
    <script>
        //add the active class to the home nav-item to highlight it
        $({% block current-nav-id %}{% endblock %}).addClass('active');
    </script>


        <script>
{#            Javascript for responsive menu#}
            function responsiveView() {
                var x = document.getElementById("top-navbar");
                if (x.className === "nav-bar") {
                    x.className += " responsive";
                } else {
                    x.className = "nav-bar";
                }
            }
        </script>

{#        <div class="submenu">#}
{#            {% block submenu %}{% endblock %}#}
{#        </div>#}
    </header>


{% block content %}{% endblock %}

</body>
</html>

meal_count/templates/meal_count/manage.html
{% extends "meal_count/base.html" %}
{% load staticfiles %}

{#HTML Template for the Director management page#}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'meal_count/managestyle.css' %}">
{% endblock %}

{% block scripts %}
    <script src="{% static 'meal_count/manage_scripts.js' %}"></script>
{% endblock %}

{% block submenu %}
    <div style="background-color: #AA7439; text-align: center; margin-top:-10px;">
        Under Construction
    </div>
    <a class="clickable" href="#status-panel">Status Options</a>
    <a class="clickable" href="#diet-panel">Diets</a>
    <a class="clickable" href="#meal-panel">Meals</a>
    <a class="clickable" href="/manage/users">Users</a>
{% endblock %}

{% block content %}
    <div class="panel" id="status-panel">
        <div class="panel-title">Status Options</div>
        {% for option in center.statusoption_set.all %}
        <div class="widget">
            <div class="widget-title ">{{ option.name }}</div>
            <table class="settings-table">
                {% csrf_token %}
                <tr>
                    <td class="widget-label">Code:</td>
                    <td class="widget-data">{{ option.abbreviation }}</td>
                </tr>
                <tr>
                    <td class="widget-label">Enabled</td>
                    <td class="widget-data"><input class="status-active-cb" id="{{ option.id }}" type="checkbox" {% if option.active %}checked{% endif %}></td>
                </tr>
{#                <tr>#}
{#                    <td class="widget-label">Prep Time</td>#}
{#                    <td class="widget-data">{{ option.prep_time }} hr{{ option.prep_time|pluralize }}</td>#}
{#                </tr>#}
                {% if option.can_edit %}
                    <tr class="widget-submit">
{#                        <td><a class="clickable">Edit</a></td>#}
                        <td colspan="2"><a class="clickable del-opt" id="{{ option.id }}">Delete</a></td>
                    </tr>
                {% endif %}
            </table>
        </div>
        {% endfor %}

        <div class="widget" id="new-widget">
            <div class="widget-title">New Status Option</div>
            <table>
                <form action="/manage/add_opt" method="post" id="add-opt-form">
                    <tr>
                        <td class="widget-label">Name:</td>
                        <td class="widget-data"><input type="text" name="opt_name" maxlength="10" style="width:120px;"></td>
                    </tr>
                    <tr>
                        <td class="widget-label">Code:</td>
                        <td class="widget-data"><input type="text" name="opt_code" maxlength="2" style="width:60px;"></td>
                    </tr>
{#                    <tr>#}
{#                        <td class="widget-label">Prep Time:</td>#}
{#                        <td class="widget-data"><input type="text" name="opt_preptime" maxlength="2" style="width:60px;"> hrs</td>#}
{#                    </tr>#}
                    <tr>
                        <td colspan="2" class="widget-submit clickable" id="submit-add-form"><a>Add</a></td>
                    </tr>
                </form>
            </table>
        </div>
    </div>

    <div class="panel" id="meal-panel">
        <div class="panel-title">Meals</div>
        {% for meal in center.mealoption_set.all %}
        <div class="widget">
            <div class="widget-title ">{{ meal.name }}</div>
            <table class="settings-table">
                {% csrf_token %}
                <tr>
                    <td class="widget-label">Code</td>
                    <td class="widget-data">{{ meal.code }}</td>
                </tr>
                <tr>
                    <td class="widget-label">Time</td>
                    <td class="widget-data">{{ meal.meal_time}}</td>
                </tr>
                {% if meal.can_edit %}
                    <tr class="widget-submit">
                        <td><a class="clickable">Edit</a></td>
                        <td><a class="clickable del-meal" id="{{ meal.id }}">Delete</a></td>
                    </tr>
                {% endif %}
            </table>
        </div>
        {% endfor %}

        <div class="widget" id="new-widget">
            <div class="widget-title">New Diet</div>
            <table>
                <form action="/manage/add_meal" method="post" id="add-meal-form">
                    <tr>
                        <td class="widget-label">Name:</td>
                        <td class="widget-data"><input type="text" name="meal_name" maxlength="16" style="width:150px;"></td>
                    </tr>
                    <tr>
                        <td class="widget-label">Code:</td>
                        <td class="widget-data"><input type="text" name="meal_code" maxlength="6" style="width:60px;"></td>
                    </tr>
                    <tr>
                        <td class="widget-label">Time:</td>
                        <td class="widget-data"><input type="time" name="meal_time" maxlength="6" style="width:100px;"></td>
                    </tr>
                    <tr>
                        <td colspan="2" class="widget-submit clickable" id="submit-meal-form"><a>Add</a></td>
                    </tr>
                </form>
            </table>
        </div>
    </div>

    <div class="panel" id="diet-panel">
        <div class="panel-title">Diets</div>
        {% for diet in center.diet_set.all %}
        <div class="widget">
            <div class="widget-title ">{{ diet.name }}</div>
            <table class="settings-table">
                {% csrf_token %}
                <tr>
                    <td class="widget-label">Code</td>
                    <td class="widget-data">{{ diet.code }}</td>
                </tr>
                <tr>
                    <td class="widget-label">Description</td>
                    <td class="widget-data">{{ diet.description }}</td>
                </tr>
                {% if diet.can_edit %}
                    <tr class="widget-submit">
                        <td><a class="clickable ed-diet" id="{{ diet.id }}">Edit</a></td>
                        <td><a class="clickable del-diet" id="{{ diet.id }}">Delete</a></td>
                    </tr>
                {% endif %}
            </table>
        </div>
        {% endfor %}

        <div class="widget" id="new-widget">
            <div class="widget-title">New Diet</div>
            <table>
                <form action="/manage/add_diet" method="post" id="add-diet-form">
                    <tr>
                        <td class="widget-label">Name:</td>
                        <td class="widget-data"><input type="text" name="diet_name" maxlength="10" style="width:120px;"></td>
                    </tr>
                    <tr>
                        <td class="widget-label">Code:</td>
                        <td class="widget-data"><input type="text" name="diet_code" maxlength="2" style="width:60px;"></td>
                    </tr>
                    <tr>
                        <td class="widget-label">Description</td>
                        <td class="widget-data"><input type="text" name="diet_description" maxlength="30" style="width:150px;"></td>
                    </tr>
                    <tr>
                        <td colspan="2" class="widget-submit clickable" id="submit-add-diet-form"><a>Add</a></td>
                    </tr>
                </form>
            </table>
        </div>
    </div>
{% endblock %}

meal_count/templates/meal_count/manage_users.html
{% extends "meal_count/base.html" %}
{% load staticfiles %}

{#HTML Template for the Director management page#}

{% block styles %}
{#    <link rel="stylesheet" type="text/css" href="{% static 'meal_count/managestyle.css' %}">#}
    <link rel="stylesheet" type="text/css" href="{% static 'meal_count/styles/managestyle.css' %}">
{% endblock %}

{% block scripts %}
    <script src="{% static 'meal_count/manage_scripts.js' %}"></script>
    <script src="{% static 'meal_count/scripts/managescripts.js' %}"></script>
{% endblock %}

{% block submenu %}
    <div style="background-color: #AA7439; text-align: center; margin-top:-10px;">
        Under Construction
    </div>
    <a class="clickable" href="/manage#status-panel">Status Options</a>
    <a class="clickable" href="/manage#diet-panel">Diets</a>
    <a class="clickable" href="/manage#meal-panel">Meals</a>
    <span>Users</span>
{% endblock %}

{% block content %}
{#    Panel with a list of items#}
    <div class="half-panel" id="list-panel">
        <div id="actions-bar">
            <span class="header">Actions</span>
            <br>
            <div class="ab-filter-div">
                <a class="clickable">Active Users</a>
                <a class="clickable">Deactivated Users</a>
                <a class="clickable">Deactivated Users</a>
            </div>
        </div>
        <div id="list-area">
            <ul id="main-list">
                {% for item in main_list %}
{#                    when a user clicks on this list item, the page sends a get request with the person's username#}
{#                    This is pagetype specific.#}
{#                    Add color to current user#}
                    {% if pagetype == 'users' %}
                        <li class="list-item {% if item.user.username == current_item.username %}current{% endif %}" onclick="window.location='/manage/users/{{ item.user.username }}'">{{ item.name }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>

    {#    Panel with a list of details and settings#}
    <div class="half-panel" id="details-panel">
    {% if pagetype == 'users' and current_item != None%}{% with user=current_item %}
        <h1 class="details-title">
            {{ user.person.name }}
        </h1>
        <div class="details-detail">
            <form action="/manage/change_person_status" method="post" id="user_status">
                {% csrf_token %}
                <input type="hidden" name="person-id" value="{{ user.person.id }}">
                <input type="checkbox" id="user-status-input" {% if user.person.active %}checked{% endif %}>
                <label>Active User</label>
            </form>
        </div>
    {% endwith %}{% endif %}
    </div>

{% endblock %}